### 1. Carrega o arquivo com as sentenças (Córpus da Gabriela)

In [1]:
import pandas as pd

In [2]:
data_frame = pd.read_csv('dataset_features.csv')

In [3]:
inputs = data_frame.iloc[:,1:10].values
outputs = data_frame['classificacao']

inputs.shape, outputs.shape

((4000, 9), (4000,))

In [4]:
data_frame.head(1)

classificacao  entidades_nomeadas  adjetivos  triggers  intensifiers  \
0              1                   0          1         1             1   

   modifiers  quotation_marks  repeated_punctuation  letters_repetition  \
0          1                0                     0                   0   

   word_repetition  
0                0

### 2. Identificação da importância de cada feature
https://medium.com/@aneesha/recursive-feature-elimination-with-scikit-learn-3a2cbdf23fb7

https://machinelearningmastery.com/feature-selection-machine-learning-python/

#### 2.1. Uitilizando Árvore de Decisão

In [24]:
# https://blog.datadive.net/selecting-good-features-part-iv-stability-selection-rfe-and-everything-side-by-side/
# Feature Importance using Decision Tree
from sklearn import datasets

from sklearn import metrics
from sklearn import tree

classificador = tree.DecisionTreeClassifier()
classificador.fit(inputs, outputs)

columns_names = list(data_frame.iloc[:,1:10].columns.values)

# display the relative importance of each attribute
# print(data_frame.iloc[:,1:10].head(0))
# print(classificador.feature_importances_)

# print ("Features sorted by their score:")
print (sorted(zip(map(lambda x: round(x, 4), classificador.feature_importances_), 
                 columns_names), reverse=True))

[(0.3666, 'repeated_punctuation'), (0.1154, 'word_repetition'), (0.0983, 'adjetivos'), (0.0922, 'letters_repetition'), (0.0796, 'quotation_marks'), (0.0787, 'modifiers'), (0.0666, 'intensifiers'), (0.058, 'entidades_nomeadas'), (0.0446, 'triggers')]


In [28]:
# Feature Importance using Logistic Regression
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

classificador = LogisticRegression()

columns_names = list(data_frame.iloc[:,1:10].columns.values)

# create the RFE model and select 1 attribute
rfe = RFE(classificador, 1)
rfe = rfe.fit(inputs, outputs)

# summarize the selection of the attributes
# print(data_frame.iloc[:,1:10].head(0))
# print(rfe.support_)
# print(rfe.ranking_)

print (sorted(zip(map(lambda x: round(x, 4), rfe.ranking_), 
                 columns_names), reverse=False))

[(1, 'repeated_punctuation'), (2, 'adjetivos'), (3, 'quotation_marks'), (4, 'modifiers'), (5, 'letters_repetition'), (6, 'intensifiers'), (7, 'entidades_nomeadas'), (8, 'triggers'), (9, 'word_repetition')]


In [30]:
# Feature Importance using SVM
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn import svm

classificador = svm.SVC(gamma='auto', C=1.0, kernel='linear', probability=False)

# create the RFE model and select 3 attributes
rfe = RFE(classificador, 1)
rfe = rfe.fit(inputs, outputs)

columns_names = list(data_frame.iloc[:,1:10].columns.values)

# summarize the selection of the attributes
# print(data_frame.iloc[:,1:10].head(0))
# print(rfe.support_)
# print(rfe.ranking_)

print (sorted(zip(map(lambda x: round(x, 4), rfe.ranking_), 
                 columns_names), reverse=False))

[(1, 'repeated_punctuation'), (2, 'adjetivos'), (3, 'modifiers'), (4, 'quotation_marks'), (5, 'triggers'), (6, 'word_repetition'), (7, 'intensifiers'), (8, 'letters_repetition'), (9, 'entidades_nomeadas')]


In [ ]:
# Feature Importance using MLP Neural Network
# https://www.kaggle.com/arpitvit/mlp-with-rfe-feature-selection
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.neural_network import MLPClassifier

classificador = MLPClassifier(activation='relu', solver='adam', max_iter=10000, alpha=1e-10)

# create the RFE model and select 3 attributes
rfe = RFE(classificador, 1)
rfe = rfe.fit(inputs, outputs)

# summarize the selection of the attributes
print(data_frame.iloc[:,1:10].head(0))
print(rfe.support_)
print(rfe.ranking_)

In [26]:
# # http://minerandodados.com.br/index.php/2018/05/21/feature-selection-bala-de-prata/
# from sklearn import feature_selection
# fs = feature_selection.SelectPercentile(feature_selection.f_classif, percentile=100)
# # model = feature_selection.SelectKBest(score_func=feature_selection.f_regression, k=9)
# X_treino_fs = fs.fit_transform(inputs, outputs)

# # results = model.fit(df[columns], df['qsec'])

# print(fs.scores_)
# print(fs.pvalues_)

# # x = pd.DataFrame(X_treino_fs)
# # x

# df1.head()

In [10]:
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
import pandas
import numpy
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

# feature extraction
test = SelectKBest(score_func=chi2, k='all') #4
fit = test.fit(inputs, outputs)

columns_names = list(data_frame.iloc[:,1:10].columns.values)

# summarize scores
numpy.set_printoptions(precision=3)
scores = fit.scores_
print(scores)

features = fit.transform(inputs)

# summarize selected features
print(features[0:10,:])

print (sorted(zip(map(lambda x: round(x, 4), scores), 
                 columns_names), reverse=True))

[ 2.921 12.93   1.065  3.458  1.714 14.538 74.572 10.755 25.53 ]
[[0 1 1 1 1 0 0 0 0]
 [0 0 1 0 1 0 1 0 0]
 [0 0 1 0 1 0 0 1 0]
 [1 0 1 0 1 1 1 0 0]
 [0 0 1 0 0 0 1 0 0]
 [0 0 1 0 1 0 0 0 0]
 [0 1 1 1 1 0 0 0 0]
 [0 1 1 0 1 0 1 0 1]
 [0 0 1 0 1 0 0 0 0]
 [1 0 1 0 1 0 0 0 0]]
[(74.5716, 'repeated_punctuation'), (25.53, 'word_repetition'), (14.5385, 'quotation_marks'), (12.9301, 'adjetivos'), (10.7553, 'letters_repetition'), (3.4575, 'intensifiers'), (2.921, 'entidades_nomeadas'), (1.7138, 'modifiers'), (1.0654, 'triggers')]
